### PR TITLE
Bombs!!

### LINKED ISSUE #9: Bomb Class
A Class needs to be created for a bomb.

Basic Class requirements
- Position: Most likely a Vector2I
- Countdown: A float to keep track of time left over
- Update function: Removes delta time from countdown returning a bool indicating and explosion.

Functionality could be expanded on this issue. Once a bomb explodes there will need to be some way of indicating on the map that there is now fire in the cell as well as logic checks to destroy walls.

Current collision logic uses the map to check neighbouring cells. As such we will most likely need to update the when a bomb is placed to insure player cannot enter a cell with a bomb

### PR DESCRIPTION
**Pull request by WSeegers**
Closes #9 

-- Bombs can now be placed with the spacebar key.
-- Bombs are removed after FUSE_TIME
-- No logic exists for explosions or collisions

### CODE REVIEW

**Review by TalPat — CHANGES_REQUESTED** [review]
On launch, the player spontaneously floats right and occasionally clips through soft walls during initial float (only tested on campus macs)

**Comment by dpoulter-WTC** [comment]
On my linux machine there is no player at all and if you spam spacebar then bombs get placed randomly.

**Review by agabrie — COMMENTED** [review]
player always moving right until right key is actually pressed, occasionally clips through walls (campus iMac)

**Comment by charlchi** [comment]
I wasn't really sure how to make code changes to this PR, so I made a new PR #22 with fixes to the issues in this pull request(player moving out of the screen at the start, too much player clipping, random bombs)

**Comment by WSeegers** [comment]
@TalPat Initial movement issue has been corrected.

@dpoulter-WTC Will take a look at the meeting

**Comment by WSeegers** [comment]
@charlchi you pull the branch onto your repo, and make a pull request on the the branch you wish to change

**Review by TalPat — APPROVED** [review]
All working

**Review by agabrie — APPROVED** [review]

**Pull request merged**
