### PR TITLE
Animation

### PR DESCRIPTION
**Pull request by TalPat**
Animation implemented on character and final models used for characters and enemies.
Some texture artifacting may occur on ubuntu.
Pathing issue solved, the program can be executed from any location.
Render is separated to a new thread.
Clock added to renderer, may be removed, only used for framerate tracking.

!!Orientation of multiple enemies of the same type is currently not functioning correctly.

### CODE REVIEW

**Comment by agabrie** [comment]
add default enemy model

**Comment by TalPat** [comment]
Giraffe added as default model, will be used when enemy type is not recognised by the renderer.

**Review by MEWestvig — APPROVED** [review]
Looks great!

**Review by dpoulter-WTC — APPROVED** [review]
Nice nice

**Pull request merged**
