### PR TITLE
Working movement MVP

### PR DESCRIPTION
**Pull request by WSeegers**
**NB!** This commit should be reviewed by entire team. 
Please pull and compile the code as this will serve as our base going forward.

I realise that this is a large commit, but as discussed this was a necessary evil to try kick off.

--Change to C++17 as 20 is not fully supported yet
--Simplified the Engine to only handle player movement and collisions.
--Added simple random creations of destructible cells.
--Added simple (Dirty) renderer to assist with testing engine.
--Input class is currently not functional, keys are hard code.

This should make it easier to iterate on this project. The use of classes has been purposefully explicit in the hope to make is generally readable and expandable. I feel the based on out skill level as a team and the requirements of the project, attempting to make "optimised code" by doing away abstractions will complicate things more than they need to be. 

Currently the render is the only code that is not in a somewhat appropriate format.

### CODE REVIEW

**Review by TalPat — APPROVED** [review]
Seems like a good place to start

**Review by dpoulter-WTC — APPROVED** [review]
All seems to be good. Just one issue with collision on MacOS

**Review by MEWestvig — APPROVED** [review]
All working. Happy to merge

**Comment by WSeegers** [comment]
#6 Issue for Mac opened

**Pull request merged**
